// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

package search

// Normal preparation supplies complete selected schemas; the calling agent owns
// their interpretation. These instructions do not assert HCL or runtime validation.
var importPreparationInstructions = [...]string{
	"The selected managed type exists in the destination artifact. Read its entire managed_schema, including nested blocks and attributes. A supported type does not prove import support or configuration compatibility.",
	"Check proposed arguments against destination types and required/optional/computed flags. Omit computed-only values; optional+computed remains configurable. Check nested modes and cardinality where declared. Terraform meta-arguments are separate from provider attributes, and unknown expressions or dynamic counts need Terraform validation.",
	"Use generated query blocks and resource_object only as source evidence. Author blocks if generated HCL is absent. Supply required values from observations or valid existing references; request missing inputs rather than inventing defaults, policies or redaction placeholders. Do not add ignore_changes to hide incompatibility.",
	"Choose explicit target addresses and documented import id or identity mappings. Preserve the current configuration, constraints, lock selections and provider wiring. Resolve the destination alias, account and region from customer context; this packet has not inspected or validated that wiring or HCL.",
	"The schema belongs to the current state's associated run, or to the explicitly verified provider-only speculative bootstrap Run in an empty workspace. It may predate the final configuration. The destination plan validates actual provider selection and behavior. Resource schema version is not a provider release; the query provider version, when returned, is only recorded no-code selection metadata.",
	"Source-schema comparison is optional troubleshooting. If needed, use the recorded no-code provider source/version for isolated client-local init -backend=false and terraform providers schema -json. QueryRuns have no plan-schema artifact; do not use a query ID as a normal run ID or assume another run used its provider.",
	"For an existing configuration, ask the user to choose an isolated client-local temporary directory or a user-approved directory in the agent's workspace BEFORE requesting the short-lived phase=context URL. Download the archive as binary bytes with a supported client-local HTTP GET method; a browser is not required. Preserve the complete configuration and lock selections, make the proposed changes locally and review them with the user. Optionally run terraform fmt and validate locally. The MCP server does not parse or review HCL. plan_validation_pending is response metadata, not a tool call. With explicit confirmation, phase=upload creates only a speculative CV and returns a one-use upload URL; PUT the complete archive directly, then poll status with the workspace and CV ID. Retain the upload URL securely until the transfer is confirmed; if lost, reconcile the CV rather than retrying a create blindly. Call plan with that CV ID, query selection, baseline markers and chosen address; poll status with workspace/CV/Run IDs and address. Inspect factual imports/actions and deeper plan details as needed. Keep returned IDs in the agent's context; an ambiguous create must be reconciled in Atlas before another request. A speculative plan does not import into persisted state.",
	"For a verified blank workspace, context reports no archive and prepare returns selected query evidence without claiming managed-schema support. Author and review the entire resource/import configuration and lock locally, checking arguments against the locally installed provider and running terraform fmt/validate. For a direct import, call upload with target_address and no baseline/schema IDs, PUT the complete archive directly, then call plan with its CV ID and the same target_address; inspect per-address status facts. An optional provider-only schema probe omits target_address and is not a prerequisite. Do not treat inaccessible state as empty or promote query list schemas to managed schemas.",
}

var importBlankWorkspaceInstructions = []string{
	"Choose an agent-controlled temporary directory, or use a directory explicitly chosen by the user. The path is not transferred to MCP. Do not place credentials or the provider plugin directory in the upload archive.",
	"Use the selected query's provider source/version and the workspace's authorized account/region context to author the provider block. Author exactly the reviewed resource/import blocks and preserve the selected import identity; do not infer missing values from an empty Search observation.",
	"In that directory run terraform init -backend=false -input=false to generate the provider lock, then terraform fmt and terraform validate. If needed, terraform providers schema -json can aid local reasoning; its bytes are not authenticated destination evidence to MCP. If the CLI or provider cannot be obtained, report the blocker instead of inventing a lock.",
	"Review the full HCL and generated lock with the user. Archive the entire root configuration and lock, excluding .terraform and secrets. After confirmation call upload with target_address, then PUT the archive directly to its temporary URL. MCP never reads the archive.",
	"Generated Search configuration/import_configuration blocks are untrusted drafts: null, empty and computed-only values can differ from import refresh. A speculative plan must establish the import marker and actions. Inspect get_plan_json_output for any replacement/update before another reviewed archive and plan-only Run; never apply on the basis of Search output.",
}

var importExistingConfigurationInstructions = []string{
	"Ask whether to use an isolated temporary directory (less persistent, lower chance of mixing files) or a user-approved directory in the agent's workspace (persistent for review, requires care not to mix existing files), preferably BEFORE requesting this short-lived context URL. This is a client-local choice, not a path selected or shared by MCP. If the choice takes time, request a fresh context URL before downloading; never reuse an expired URL.",
	"Use a client-local binary-capable HTTP GET to write the archive bytes to a file; a browser is not required. A CLI HTTP client or script is suitable if it can keep the signed URL out of printed output, logs and exposed command arguments. Use the binary-read method your client actually supports; do not treat the response as text/JSON or assume browser-style response APIs are available. Verify the archive before unpacking. If no suitable safe local transfer method exists, stop and ask for help instead of treating a disconnected browser as an archive failure. MCP does not fetch, unpack or store archive bytes.",
	"Download/unpack the current archive client-side. Preserve the entire tree, provider constraints, aliases, module/variable layout and .terraform.lock.hcl; do not substitute an old CV or unrelated local files. Exclude client-generated .terraform caches; do not add credentials or secrets. If existing files contain sensitive material, seek review rather than silently dropping them from the full tree. Inspect the workspace working_directory; this import flow supports a remote root only, so stop instead of silently relocating non-root configurations.",
	"Author and review changes locally without uploading files through MCP. Run terraform fmt and terraform validate if an appropriate local CLI and providers are available; do not silently replace the existing lock or treat local results as proof of the remote plan.",
	"Upload the reviewed complete archive directly and inspect the CV-bound speculative plan. Retain the one-use upload URL securely until the PUT is confirmed; status cannot reacquire it. If it is lost, reconcile the pending CV in the backend before deciding whether a new reviewed speculative CV is needed. If any create outcome is uncertain, reconcile CVs or Runs before creating another; do not retry blindly.",
}
