// Copyright IBM Corp. 2026
// SPDX-License-Identifier: MPL-2.0

package importworkflow

// importCodes lists every diagnostic and note code the import tools emit, with
// what each means. TestEveryImportCodeIsRegistered keeps this table and the
// source in step: emit a code as a string literal and add it here.
var importCodes = map[string]string{
	"backend_client_unavailable":                         "No usable backend credentials or client for this request.",
	"backend_evidence_unavailable":                       "HCP Terraform did not return the evidence the call needs (server error or unexpected response).",
	"baseline_changed":                                   "The workspace, current configuration, configuration root setting or current state changed since the first read.",
	"bindings_incomplete":                                "verify_import_plan needs a candidate_id and target_address binding for every selected candidate.",
	"bindings_invalid":                                   "A binding names an unknown candidate or an invalid or duplicate target address.",
	"blank_workspace_baseline_changed_or_unsupported":    "A workspace that looked blank now has a configuration, or its state could not be confirmed absent.",
	"blank_workspace_has_state":                          "The workspace has no current configuration but already has state, so it is not a blank workspace.",
	"blank_workspace_no_target_schema":                   "Blank workspace: no target provider schema exists, so managed_type_support and identity_support are unknown.",
	"carry_candidate_id_mismatch":                        "A binding's candidate_id is not in the carry block.",
	"carry_digest_mismatch":                              "The carry block was changed after prepare_import returned it.",
	"carry_invalid":                                      "The carry block is missing or malformed.",
	"configuration_baseline_unavailable":                 "The workspace has no current configuration version to use as a baseline.",
	"configuration_download_location_invalid":            "HCP returned an archive location that fails the URL checks (scheme, host or credentials).",
	"configuration_download_location_unavailable":        "HCP did not return a redirect location for the configuration archive.",
	"configuration_download_unavailable":                 "The configuration archive download request could not be built or was refused.",
	"configuration_root_setting_unsupported":             "The target workspace has a configuration root setting (working_directory), which is not supported yet; the agent stops before asking for an authoring directory.",
	"configuration_source_not_uploaded":                  "The configuration version exists but its archive was never uploaded.",
	"configuration_source_unavailable":                   "The configuration version is missing, unreadable or has an invalid ID.",
	"configuration_version_not_current":                  "The requested configuration version is neither the workspace's current one nor the state run's configuration version.",
	"confirm_speculative_run_required":                   "confirm_speculative_run=true is required after the user's single confirmation.",
	"current_state_unavailable_or_inaccessible":          "The workspace's current state version could not be read.",
	"cursor_invalid":                                     "The paging cursor is malformed or does not match a result in this query.",
	"cursor_query_mismatch":                              "The paging cursor belongs to a different query run.",
	"cv_create_outcome_unknown":                          "The configuration version create request failed after it may have been sent; reconcile in HCP Terraform, do not retry blindly.",
	"cv_create_response_invalid":                         "HCP returned a configuration version that is not speculative, uploadable and auto-queue off as requested.",
	"evidence_access_denied":                             "HCP Terraform denied access to the requested evidence.",
	"evidence_depth_limit":                               "Evidence JSON nests deeper than the decoder allows.",
	"evidence_json_invalid":                              "Evidence JSON is malformed or has trailing data.",
	"evidence_read_interrupted":                          "Reading evidence was interrupted (timeout or cancellation).",
	"evidence_size_limit":                                "A response is larger than the bounded reader allows.",
	"execution_cv_membership_limit":                      "Too many configuration versions to verify membership within the bound.",
	"execution_cv_membership_unverified":                 "The configuration version could not be confirmed to belong to this workspace.",
	"execution_cv_not_speculative":                       "The configuration version is not a speculative, non-provisional, auto-queue-off version.",
	"execution_cv_not_uploaded":                          "The configuration version has not finished uploading.",
	"execution_cv_workspace_mismatch":                    "The configuration version belongs to another workspace.",
	"execution_input_invalid":                            "A create input (organization, workspace or configuration version ID) is empty or malformed.",
	"execution_source_not_supported":                     "The workspace is not eligible: it is not remote execution mode, has a configuration root setting, or is VCS-backed.",
	"import_input_invalid":                               "A create call is missing or has invalid organization, workspace, baseline or configuration version fields.",
	"input_invalid":                                      "A prepare_import input is missing or invalid (names, selections, candidate IDs).",
	"list_total_equals_default_limit":                    "A list returned exactly 100 results, Terraform's default limit, so it may have been cut off.",
	"managed_schema_invalid":                             "A managed or identity schema in the plan schema artifact is malformed.",
	"managed_schema_type_missing":                        "A selected managed type is not in the target provider schema.",
	"organization_not_allowed":                           "The organization is not on this server's allowlist.",
	"plan_address_duplicate":                             "The plan lists the same resource address more than once.",
	"plan_drift_evidence_invalid":                        "The plan's resource drift entries are malformed.",
	"plan_evidence_incomplete":                           "The plan JSON is incomplete, errored or not a finished plan.",
	"plan_import_evidence_invalid":                       "A plan import entry is malformed or lacks the expected fields.",
	"plan_resource_limit":                                "The plan has more resource changes than the verifier will read.",
	"query_duplicate_identity":                           "Two query results share the same provider and identity.",
	"query_evidence_incomplete":                          "The query log is incomplete (no list completion or missing records).",
	"query_evidence_invalid":                             "The query log is malformed or has records out of order.",
	"query_evidence_size_limit":                          "The query log is larger than the 4 MiB bound.",
	"query_evidence_unverified":                          "The query run is not finished, does not match the requested ID or has no workspace.",
	"query_generated_block_conflict":                     "A result's generated configuration and its import block disagree.",
	"query_generated_block_size_limit":                   "A result's generated resource or import block exceeds 32 KiB.",
	"query_identity_invalid":                             "A query result's identity cannot be encoded.",
	"query_ownership_unverified":                         "The query run could not be confirmed to belong to the requested organization.",
	"query_provenance_unavailable":                       "The query run's no-code query or workspace link could not be confirmed.",
	"query_provider_ambiguous":                           "More than one query provider matches a result type.",
	"query_provider_source_unresolved":                   "A query provider's source address could not be resolved.",
	"query_reported_error":                               "The query log contains a Terraform error diagnostic.",
	"query_workspace_mismatch":                           "The query run belongs to a different workspace than the target.",
	"resource_attributes_not_captured":                   "No matching row carries resource attributes, so an absent tags field means not captured; re-run with generate_config_out true.",
	"resource_attributes_partly_captured":                "Some matching rows carry no resource attributes; an absent tags field on those rows means not captured.",
	"run_association_unverified":                         "The created run does not match the expected workspace, configuration version or plan-only options.",
	"run_create_outcome_unknown":                         "The run create request failed after it may have been sent; reconcile in HCP Terraform, do not retry blindly.",
	"run_not_plan_only":                                  "The run is not a plan-only run created by create_import_run.",
	"schema_download_required":                           "The plan schema endpoint answered with a redirect (HTTP 307) instead of the schema; the server never follows it.",
	"schema_format_unsupported":                          "The provider schema artifact has an unsupported format_version.",
	"schema_provider_missing":                            "The provider is missing from the plan schema artifact.",
	"schema_source_access_denied":                        "Access to the plan schema artifact was denied, even after one retry through the stable endpoint.",
	"schema_source_cli_unsupported":                      "The plan schema endpoint answered HTTP 422: the schema artifact does not exist for this run's Terraform version (below 0.12).",
	"schema_source_http_error":                           "The plan schema endpoint returned an unexpected HTTP error.",
	"schema_source_pending":                              "The plan that produced the schema has not finished (HTTP 204).",
	"schema_source_plan_unavailable":                     "The run that produced the current state has no plan, so no schema artifact exists.",
	"schema_source_unavailable":                          "The plan schema artifact could not be found.",
	"schema_source_uses_different_configuration_version": "The schema comes from a run that used a different configuration version than the workspace's current one.",
	"schema_source_workspace_mismatch":                   "The run that produced the schema belongs to another workspace.",
	"selected_candidate_not_found":                       "A selected candidate_id is not in the query run.",
	"selected_identity_overlap":                          "Two selections name the same resource identity.",
	"snapshot_changed_restart_paging":                    "The query log changed between pages; restart paging from the first page.",
	"state_producing_run_missing":                        "The current state has no readable run, so its schema and configuration cannot be found.",
	"target_config_not_downloadable":                     "The state run's configuration version is missing, not uploaded, archived or errored.",
	"target_schema_not_read_from_hcp":                    "The agent must obtain the target schema itself (the state's run has no plan).",
	"terraform_version_below_1_12_identity_unavailable":  "The target's Terraform version is below 1.12, so identity import blocks are unavailable.",
	"terraform_version_unsupported":                      "The target's Terraform version is below 1.5, which this workflow does not support.",
	"workspace_execution_mode_local":                     "The workspace uses local execution mode; guide-only, nothing is verified.",
	"workspace_ownership_unverified":                     "The workspace could not be confirmed to belong to the requested organization.",
}
